# Generated by Django 3.0.8 on 2020-08-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('token', models.CharField(max_length=64, null=True)),
                ('nickname', models.CharField(default='匿名用户', max_length=15)),
                ('gender', models.CharField(default='男', max_length=1)),
                ('province', models.CharField(max_length=5, null=True)),
                ('city', models.CharField(max_length=5, null=True)),
                ('county', models.CharField(max_length=5, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('blog', models.URLField(null=True)),
                ('qq', models.CharField(max_length=15, null=True)),
                ('msn', models.CharField(max_length=50, null=True)),
                ('brief', models.CharField(default='暂无简介', max_length=100)),
                ('avatar', models.ImageField(default='avatar/default.gif', upload_to='avatar')),
                ('vip_level', models.PositiveSmallIntegerField(default=0)),
                ('closing_date', models.DateTimeField()),
                ('authentication', models.CharField(default='未认证', max_length=5)),
                ('search_by_phone', models.BooleanField(default=True)),
                ('recommend_phone', models.BooleanField(default=True)),
                ('who_can_comment', models.CharField(max_length=5)),
                ('comment_protect', models.BooleanField(default=False)),
                ('receive_from_user', models.CharField(max_length=5)),
                ('img_comment', models.BooleanField(default=True)),
                ('time_range', models.CharField(max_length=4)),
                ('same_city_show', models.BooleanField(default=True)),
                ('special_adv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('f', models.CharField(max_length=15)),
                ('video', models.FileField(null=True, upload_to='video')),
                ('zan', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('collection', models.ManyToManyField(related_name='user_collect_weibo', to='api.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_write_weibo', to='api.User')),
                ('user_ban_weibo', models.ManyToManyField(related_name='user_ban_weibo_set', to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='WeiboImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.ImageField(upload_to='weibo_img')),
                ('weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Weibo')),
            ],
        ),
        migrations.CreateModel(
            name='UserVtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt', models.CharField(max_length=5)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='api.User')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserBanWeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Weibo')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_vt_user',
            field=models.ManyToManyField(related_name='user_vt_user_set', through='api.UserVtUser', to='api.User'),
        ),
        migrations.CreateModel(
            name='KeyWordBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=15)),
                ('user', models.ManyToManyField(to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('zan', models.PositiveIntegerField(default=0)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set_parent', to='api.Comment')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set_reply_to', to='api.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Weibo')),
            ],
        ),
    ]
