# Generated by Django 3.0.8 on 2020-08-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='type',
            field=models.CharField(default='公开', max_length=3),
        ),
    ]
