# Generated by Django 3.0.8 on 2020-08-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200823_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='f',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
