# Generated by Django 3.0.8 on 2020-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200824_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
