# Generated by Django 3.0.8 on 2020-08-25 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200825_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
