# Generated by Django 3.0.8 on 2020-08-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200825_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='f',
            field=models.CharField(default='微博 HTML5 版', max_length=15),
        ),
    ]
