# Generated by Django 3.0.8 on 2020-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_vt_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_user_vt_user_set', to='api.UserVtUser'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_user_set', to='api.User'),
        ),
    ]
