# Generated by Django 3.0.8 on 2020-08-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200826_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_vt_user',
        ),
    ]
