# Generated by Django 3.0.8 on 2020-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200827_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weibo',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='weibo',
            name='comment_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weibo',
            name='share',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
