# Generated by Django 3.0.8 on 2020-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fans',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
