# Generated by Django 3.0.8 on 2020-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200830_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_vt_user',
            field=models.ManyToManyField(related_name='user_vt_user_set', through='api.UserVtUser', to='api.User'),
        ),
    ]
