# Generated by Django 3.0.8 on 2020-09-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200907_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='weibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Weibo'),
        ),
    ]
