# Generated by Django 3.0.8 on 2020-09-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200907_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='related_weibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Weibo'),
        ),
    ]
