# Generated by Django 3.0.8 on 2020-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='user_agree_weibo',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_agree_weibo', to='api.User'),
        ),
    ]
