# Generated by Django 3.0.8 on 2020-09-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200910_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibo',
            name='type',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
