# Generated by Django 3.0.8 on 2020-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200914_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='weibo',
        ),
        migrations.AddField(
            model_name='weibo',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='api.Topic'),
        ),
    ]
