# Generated by Django 3.0.8 on 2020-09-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20200917_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
