# Generated by Django 3.0.8 on 2020-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20200919_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='f',
            field=models.CharField(blank=True, default='微博 HTML5 版', max_length=32, null=True),
        ),
    ]
