# Generated by Django 3.0.8 on 2020-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20200919_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='first_images'),
        ),
        migrations.AddField(
            model_name='weibo',
            name='video_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='weibo',
            name='video_view',
            field=models.ManyToManyField(blank=True, null=True, related_name='video_view_set', to='api.User'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
