# Generated by Django 3.0.8 on 2020-08-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weibo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='category',
            field=models.ForeignKey(default='同城', on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='f',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_write_weibo', to='api.User'),
        ),
    ]
