# Generated by Django 3.0.8 on 2020-08-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200805_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='collection',
            field=models.ManyToManyField(null=True, related_name='user_collect_weibo', to='api.User'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='user_ban_weibo',
            field=models.ManyToManyField(null=True, related_name='user_ban_weibo_set', to='api.User'),
        ),
    ]
