# Generated by Django 3.0.8 on 2020-08-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200809_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibo',
            old_name='type',
            new_name='public_state',
        ),
    ]
