# Generated by Django 3.0.8 on 2020-08-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200811_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='weibo',
            field=models.ManyToManyField(null=True, to='api.Weibo'),
        ),
    ]
