# Generated by Django 3.0.8 on 2020-08-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_topic_weibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weibo',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterField(
            model_name='user',
            name='closing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
