# Generated by Django 3.0.8 on 2020-08-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200825_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservtuser',
            name='group',
        ),
    ]
