# Generated by Django 3.0.8 on 2020-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_vt_user',
            field=models.ManyToManyField(related_name='_user_user_vt_user_+', through='api.UserVtUser', to='api.User'),
        ),
    ]
