# Generated by Django 3.0.8 on 2020-09-03 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200831_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
