# Generated by Django 3.0.8 on 2020-09-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_weibo_user_agree_weibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibo',
            name='zan',
        ),
    ]
