# Generated by Django 3.0.8 on 2020-09-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_weibo_zan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreeWeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Weibo')),
            ],
        ),
        migrations.AddField(
            model_name='weibo',
            name='user_agree_weibo_2',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_agree_weibo_2_set', through='api.UserAgreeWeibo', to='api.User'),
        ),
    ]
