# Generated by Django 3.0.8 on 2020-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200913_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='content',
            field=models.TextField(default='出bug了'),
        ),
    ]
