# Generated by Django 3.0.8 on 2020-09-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200913_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='阅读', max_length=2)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('weibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Weibo')),
            ],
        ),
        migrations.DeleteModel(
            name='Read',
        ),
    ]
