# Generated by Django 3.0.8 on 2020-09-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200914_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_vt_user',
        ),
    ]
