# Generated by Django 3.0.8 on 2020-09-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200914_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agree_comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_agree_comment_set', through='api.UserAgreeComment', to='api.User'),
        ),
    ]
