# Generated by Django 3.0.8 on 2020-08-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_sth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
